/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_violas_sdk_Client_Account */

#ifndef _Included_io_violas_sdk_Client_Account
#define _Included_io_violas_sdk_Client_Account
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
