/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libra_client_ClientProxy */

#ifndef _Included_org_libra_client_ClientProxy
#define _Included_org_libra_client_ClientProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_libra_client_ClientProxy
 * Method:    nativeClientProxyNew
 * Signature: (Ljava/lang/String;SLjava/lang/String;Ljava/lang/String;ZLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_libra_client_ClientProxy_nativeClientProxyNew
  (JNIEnv *, jobject, jstring, jshort, jstring, jstring, jboolean, jstring, jstring);

/*
 * Class:     org_libra_client_ClientProxy
 * Method:    nativeClientProxyDestory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_libra_client_ClientProxy_nativeClientProxyDestory
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
