/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_violas_sdk_Token */

#ifndef _Included_io_violas_sdk_Token
#define _Included_io_violas_sdk_Token
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_violas_sdk_Token
 * Method:    nativeCreateTokenManager
 * Signature: (J[BLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_violas_sdk_Token_nativeCreateTokenManager
  (JNIEnv *, jobject, jlong, jbyteArray, jstring, jstring, jstring);

/*
 * Class:     io_violas_sdk_Token
 * Method:    nativeName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_violas_sdk_Token_nativeName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_violas_sdk_Token
 * Method:    nativeAddress
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_violas_sdk_Token_nativeAddress
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_violas_sdk_Token
 * Method:    nativeDeploy
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_violas_sdk_Token_nativeDeploy
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_violas_sdk_Token
 * Method:    nativePublish
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_violas_sdk_Token_nativePublish
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_violas_sdk_Token
 * Method:    nativeCreateToken
 * Signature: (JJ[BLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_violas_sdk_Token_nativeCreateToken
  (JNIEnv *, jobject, jlong, jlong, jbyteArray, jstring);

/*
 * Class:     io_violas_sdk_Token
 * Method:    nativeMint
 * Signature: (JJJ[BJ)V
 */
JNIEXPORT void JNICALL Java_io_violas_sdk_Token_nativeMint
  (JNIEnv *, jobject, jlong, jlong, jlong, jbyteArray, jlong);

/*
 * Class:     io_violas_sdk_Token
 * Method:    nativeTransfer
 * Signature: (JJJ[BJ)V
 */
JNIEXPORT void JNICALL Java_io_violas_sdk_Token_nativeTransfer
  (JNIEnv *, jobject, jlong, jlong, jlong, jbyteArray, jlong);

/*
 * Class:     io_violas_sdk_Token
 * Method:    nativeGetBalance
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_violas_sdk_Token_nativeGetBalance__JJJ
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_violas_sdk_Token
 * Method:    nativeGetBalance
 * Signature: (JJ[B)J
 */
JNIEXPORT jlong JNICALL Java_io_violas_sdk_Token_nativeGetBalance__JJ_3B
  (JNIEnv *, jobject, jlong, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
