/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_violas_sdk_java_Token */

#ifndef _Included_io_violas_sdk_java_Token
#define _Included_io_violas_sdk_java_Token
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_violas_sdk_java_Token
 * Method:    nativeCreateToken
 * Signature: (J[BLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_violas_sdk_java_Token_nativeCreateToken
  (JNIEnv *, jobject, jlong, jbyteArray, jstring, jstring, jstring);

/*
 * Class:     io_violas_sdk_java_Token
 * Method:    nativeName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_violas_sdk_java_Token_nativeName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_violas_sdk_java_Token
 * Method:    nativeAddress
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_violas_sdk_java_Token_nativeAddress
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_violas_sdk_java_Token
 * Method:    nativeDeploy
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_violas_sdk_java_Token_nativeDeploy
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_violas_sdk_java_Token
 * Method:    nativePublish
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_violas_sdk_java_Token_nativePublish
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_violas_sdk_java_Token
 * Method:    nativeMint
 * Signature: (JJ[BJ)V
 */
JNIEXPORT void JNICALL Java_io_violas_sdk_java_Token_nativeMint
  (JNIEnv *, jobject, jlong, jlong, jbyteArray, jlong);

/*
 * Class:     io_violas_sdk_java_Token
 * Method:    nativeTransfer
 * Signature: (JJ[BJ)V
 */
JNIEXPORT void JNICALL Java_io_violas_sdk_java_Token_nativeTransfer
  (JNIEnv *, jobject, jlong, jlong, jbyteArray, jlong);

/*
 * Class:     io_violas_sdk_java_Token
 * Method:    nativeGetBalance
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_violas_sdk_java_Token_nativeGetBalance__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_violas_sdk_java_Token
 * Method:    nativeGetBalance
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_io_violas_sdk_java_Token_nativeGetBalance__J_3B
  (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
